# Generated by Django 4.0.6 on 2022-10-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
