# Generated by Django 4.1.1 on 2022-10-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_urlmodel_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLmodel',
            new_name='urlmodels',
        ),
    ]
